# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 483bc3abca95a875afa3da3e3fc4855480deef358d405ef3dd1186ad2c34d8ff517bea4eb391c2151d668bfdf0202736eebca96fc293ffe44d231fb07eef1237

test:
  secret_key_base: c61cf8e23c3bf15dcb682f616c54eb73fa5a9ed93b3915cf56bc173e9256af1e6e711f1a090bc218846376bee6a2f131ccb5293f7e17b6a4db4a1810e4c17e94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
